import os
from sqlalchemy.orm import sessionmaker, scoped_session, declarative_base, configure_mappers
from sqlalchemy import create_engine
from sqlalchemy.engine.url import make_url
from app.utils.settings import settings


def sanitize_db_url(url: str) -> str:
    """
    Sanitizes database URL strings for SQLAlchemy compatibility.
    Fixes legacy 'postgres://' schema prefixes generated by Railway, Heroku, Render, etc.
    Strips accidental surrounding quotes and whitespace.
    Returns empty string if URL cannot be parsed by SQLAlchemy.
    """
    if not url:
        return ""
    cleaned_url = str(url).strip().strip('"').strip("'")
    if cleaned_url.startswith("postgres://"):
        cleaned_url = cleaned_url.replace("postgres://", "postgresql://", 1)
    
    try:
        make_url(cleaned_url)
        return cleaned_url
    except Exception:
        return ""


def get_db_engine(test_mode: bool = False): 
    raw_url = (
        os.getenv("DATABASE_URL")
        or os.getenv("DB_URL")
        or settings.DB_URL
        or os.getenv("POSTGRES_URL")
        or os.getenv("DATABASE_PUBLIC_URL")
        or ""
    )

    DATABASE_URL = sanitize_db_url(raw_url)

    # Fallback: construct URL from individual DB settings if single URL string is missing/invalid
    if not DATABASE_URL:
        db_user = settings.DB_USER or "postgres"
        db_pass = settings.DB_PASSWORD or "postgres"
        db_host = settings.DB_HOST or "localhost"
        db_port = settings.DB_PORT or 5432
        db_name = settings.DB_NAME or "ai_cv_generator"
        candidate_url = f"postgresql://{db_user}:{db_pass}@{db_host}:{db_port}/{db_name}?sslmode=require&channel_binding=require"
        DATABASE_URL = sanitize_db_url(candidate_url)

    # Final fallback: SQLite database to ensure the container never crashes at startup
    if not DATABASE_URL:
        DATABASE_URL = "sqlite:///./app.db"

    # SQLite needs check_same_thread=False
    connect_args = {"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {}

    return create_engine(
        DATABASE_URL,
        connect_args=connect_args,
        pool_pre_ping=True if not DATABASE_URL.startswith("sqlite") else False,
        pool_recycle=3600 if not DATABASE_URL.startswith("sqlite") else -1,
        echo=False,
    )


engine = get_db_engine()

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

db_session = scoped_session(SessionLocal)

Base = declarative_base()

# Configure mappers after all models are imported
configure_mappers()


def create_database():
    return Base.metadata.create_all(bind=engine)


def get_db():
    db = db_session()
    try:
        yield db
    finally:
        db.close()