import os
from sqlalchemy.orm import sessionmaker, scoped_session, declarative_base, configure_mappers
from sqlalchemy import create_engine
from app.utils.settings import settings


def sanitize_db_url(url: str) -> str:
    """
    Sanitizes database URL strings for SQLAlchemy compatibility.
    Fixes legacy 'postgres://' schema prefixes generated by Railway, Heroku, Render, etc.
    """
    if not url:
        return ""
    url = url.strip()
    # Railway & Heroku output 'postgres://' which SQLAlchemy 1.4+ / 2.0 rejects
    if url.startswith("postgres://"):
        url = url.replace("postgres://", "postgresql://", 1)
    return url


def get_db_engine(test_mode: bool = False): 
    raw_url = (
        settings.DB_URL
        or os.getenv("DB_URL")
        or os.getenv("DATABASE_URL")
        or os.getenv("POSTGRES_URL")
        or os.getenv("DATABASE_PUBLIC_URL")
        or ""
    )

    DATABASE_URL = sanitize_db_url(raw_url)

    # Fallback: construct URL from individual DB settings if single URL string is missing
    if not DATABASE_URL:
        db_user = settings.DB_USER or "postgres"
        db_pass = settings.DB_PASSWORD or "postgres"
        db_host = settings.DB_HOST or "localhost"
        db_port = settings.DB_PORT or 5432
        db_name = settings.DB_NAME or "ai_cv_generator"
        DATABASE_URL = f"postgresql://{db_user}:{db_pass}@{db_host}:{db_port}/{db_name}"

    return create_engine(
        DATABASE_URL,
        pool_pre_ping=True,  # Verify connections before using them
        pool_recycle=3600,   # Recycle connections after 1 hour
        pool_size=10,        # Number of connections to maintain
        max_overflow=20,     # Max additional connections when pool is full
        echo=False           # Set to True for SQL query logging
    )


engine = get_db_engine()

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

db_session = scoped_session(SessionLocal)

Base = declarative_base()

# Configure mappers after all models are imported
configure_mappers()


def create_database():
    return Base.metadata.create_all(bind=engine)


def get_db():
    db = db_session()
    try:
        yield db
    finally:
        db.close()