"""add submission activities and metadata fields

Revision ID: 0ef7222ab49c
Revises: 37b11e06368b
Create Date: 2026-08-22 23:40:11.349188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ef7222ab49c'
down_revision: Union[str, Sequence[str], None] = '37b11e06368b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_activities',
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_activities_id'), 'submission_activities', ['id'], unique=False)
    op.add_column('submissions', sa.Column('reference_id', sa.String(), nullable=False))
    op.add_column('submissions', sa.Column('target_company', sa.String(), nullable=True))
    op.add_column('submissions', sa.Column('priority', sa.String(), nullable=False))
    op.create_index(op.f('ix_submissions_reference_id'), 'submissions', ['reference_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_reference_id'), table_name='submissions')
    op.drop_column('submissions', 'priority')
    op.drop_column('submissions', 'target_company')
    op.drop_column('submissions', 'reference_id')
    op.drop_index(op.f('ix_submission_activities_id'), table_name='submission_activities')
    op.drop_table('submission_activities')
    # ### end Alembic commands ###
