"""updated the prompt table

Revision ID: ad82327e8c21
Revises: 4a5b6c7d8e9f
Create Date: 2026-08-27 05:46:36.832363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad82327e8c21'
down_revision: Union[str, Sequence[str], None] = '4a5b6c7d8e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('description', sa.String(), nullable=True))
    op.add_column('prompts', sa.Column('category', sa.String(), nullable=True))
    op.add_column('prompts', sa.Column('usage_count', sa.Integer(), nullable=False))
    op.alter_column('prompts', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompts', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('prompts', 'usage_count')
    op.drop_column('prompts', 'category')
    op.drop_column('prompts', 'description')
    # ### end Alembic commands ###
