"""add_document_rendering_fields

Revision ID: cfc93f8f4591
Revises: ad82327e8c21
Create Date: 2026-08-27 06:57:47.747244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc93f8f4591'
down_revision: Union[str, Sequence[str], None] = 'ad82327e8c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_generations', sa.Column('structured_cv_json', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('ai_generation_id', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('file_name', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('public_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'documents', 'ai_generations', ['ai_generation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'public_id')
    op.drop_column('documents', 'file_name')
    op.drop_column('documents', 'ai_generation_id')
    op.drop_column('ai_generations', 'structured_cv_json')
    # ### end Alembic commands ###
